apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

helmGlobals:
  chartHome: ../../../../

helmCharts:
  - name: helm-gitea
    releaseName: helm-gitea
    valuesFile: values-dev.yaml
resources:
  - gateway.yaml
  - httproute.yaml
