apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

helmCharts:
  - name: gitea
    repo: https://dl.gitea.com/charts/
    releaseName: gitea
    namespace: gitea # Helm template의 .Release.Namespace 설정
    version: 12.4.0
    valuesFile: values-dev.yaml
resources:
  - gateway.yaml
  - httproute.yaml

patchesStrategicMerge:
  - patch-init-secret.yaml
