apiVersion: v1
kind: Secret
metadata:
  name: gitea-inline-config
  namespace: gitea
stringData:
  cache: |-
    ADAPTER=redis
    HOST=redis+cluster://:@gitea-valkey-cluster-headless.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
  queue: |-
    CONN_STR=redis+cluster://:@gitea-valkey-cluster-headless.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
    TYPE=redis
  session: |-
    PROVIDER=redis
    PROVIDER_CONFIG=redis+cluster://:@gitea-valkey-cluster-headless.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
  database: |-
    DB_TYPE=postgres
    HOST=postgres-gitea-pgbouncer.postgres-gitea.svc.cluster.local:5432
    NAME=gitea
    USER=gitea
    PASSWD=*uc?8SxpkwXyeO@h(RKqd0Gt
